config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

	authenticated do
	  root to: 'charts#index'
	end

	root to: 'pages#home'

  resources :charts, except: [:new, :show] do
    resources :datasets, only: [:create, :update]
  end

  resources :datasets, only: [:edit, :destroy]
end

app/models/dataset.rb
class Dataset < ApplicationRecord
  belongs_to :chart

  validates :value, presence: true
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :set_dataset, only: [:edit, :update, :destroy]
  skip_before_action :authenticate_user!

  def create
    @chart = Chart.find(params[:chart_id])
    @dataset = Dataset.new(dataset_params)
    @dataset.chart = @chart
    data_save_common
  end

  def edit
    @chart = @dataset.chart
  end

  def update
    @chart = @dataset.chart
    update_common   
  end

  def destroy
    @chart = @dataset.chart
    @dataset.destroy
  end

  private

  def set_dataset
    @dataset = Dataset.find(params[:id])
  end

  def dataset_params
    params.require(:dataset).permit(:label, :value, :value_user)
  end

  def data_save_common
    @dataset.value = 0 if @chart.chart_type == "waterfall"
    if @dataset.save
      @chart.updated_at = @dataset.updated_at
      update_datasets_waterfall(@chart) if @chart.chart_type == "waterfall"
      @chart.save
      respond_to do |format|
        format.html { redirect_to edit_chart_path(@chart)}
        format.js # <-- will render `app/views/datasets/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'charts/edit' }
        format.js
      end
    end
  end

  def update_common
    @dataset.value = 0 if @chart.chart_type == "waterfall"
    if @dataset.update(dataset_params)
      @chart.updated_at = @dataset.updated_at
      update_datasets_waterfall(@chart) if @chart.chart_type == "waterfall"
      @chart.save
      respond_to do |format|
        format.html { redirect_to edit_chart_path(@chart)}
        format.js # <-- will render `app/views/datasets/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'charts/edit' }
        format.js
      end
    end
  end

  def update_datasets_waterfall(chart)
    datasets_raw = chart.datasets.order(:created_at)
    sum_result = 0
    i = 0
    datasets_raw.each do |dts|
      if i == 0
        dts.value = dts.value_user.to_i
        dts.serietype = "baseline"
        dts.offset = 0
        sum_result += dts.value
        dts.save
        i += 1
      elsif dts.value_user == "e"
        dts.value = sum_result
        dts.offset = 0
        dts.serietype = "baseline"
        dts.save
        i += 1
      elsif dts.value_user.to_i >= 0
        dts.value = dts.value_user.to_i
        dts.serietype = "plus"
        dts.offset = sum_result
        sum_result += dts.value
        dts.save
        i += 1
      else
        dts.value = -dts.value_user.to_i
        dts.serietype = "less"
        dts.offset = sum_result - dts.value
        sum_result += -dts.value
        dts.save
        i += 1
      end
    end
  end

end

app/views/datasets/_form.html.erb
<!-- This is the form used to add rows to the table -->
<%= simple_form_for([chart, dataset], remote: true) do |f| %>
  <div class="table-entry">
    <div class="left-form">
      <%= f.input :label, placeholder: 'Label', label: false, autofocus: true %>
    </div>
    <div class="right-form">
      <% if chart.chart_type == "waterfall" %>
      <%= f.input :value_user, placeholder: 'Value', label: false, hint: "type 'e' to generate baseline" %>
      <%= f.hidden_field :value %>
      <% else %>
      <%= f.input :value, placeholder: 'Value', label: false %>
      <% end %>
    </div>
    <div class="submit-form">
      <%= f.button :button do %>
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/datasets/_inline_form.html.erb
<!-- This is the form used to edit and delete rows in the table -->
<%= simple_form_for([chart, dataset], remote: true, html: { class: "table-row table-inline-entry", 'data-dataset-id' => dataset.id })  do |f| %>
  <!-- <div class="table-inline-entry"> -->
    <div class="table-cell left-form">
      <%= f.input :label, placeholder: 'Label', label: false, autofocus: true %>
    </div>
    <div class="table-cell right-form">
      <% if chart.chart_type == "waterfall" %>
        <%= f.input :value_user, placeholder: 'Value', label: false, hint: "type 'e' to generate baseline" %>
      <% else %>
        <%= f.input :value, placeholder: 'Value', label: false %>
      <% end %>
    </div>
    <div class="table-cell-btn submit-form">
      <%= f.button :button do %>
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
      <% end %>
    </div>
  <!-- </div> -->
<% end %>

app/views/datasets/_show.html.erb
<div class="table-row" data-dataset-id="<%= dataset.id %>">
  <div class="table-cell">
    <p><%= "#{dataset.label}" %></p>
  </div>
  <div class="table-cell">
    <p><%= "#{@chart.chart_type == "waterfall" ? dataset.value_user : dataset.value}" %></p>
  </div>
  <div class="table-cell-btn edit-delete">
    <%= link_to edit_dataset_path(dataset), remote: true do %>
      <i class="fa fa-pencil" aria-hidden="true"></i>
    <% end %>
    <%= link_to dataset_path(dataset), method: :delete, remote: true do %>
      <i class="fa fa-minus-circle" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

app/views/datasets/create.js.erb
function refreshForm(innerHTML) {
  const newDatasetForm = document.getElementById('new_dataset');
  newDatasetForm.innerHTML = innerHTML;
}

function addDataset(datasetHTML) {
  const datasets = document.getElementById('data-sets-table');
  datasets.insertAdjacentHTML('beforeend', datasetHTML);
}

<% if @dataset.errors.any? %>
  refreshForm('<%= j render "datasets/form", chart: @chart, dataset: @dataset %>');
<% else %>
  addDataset('<%= j render "datasets/show", dataset: @dataset %>');
  refreshForm('<%= j render "datasets/form", chart: @chart, dataset: Dataset.new %>');
<% end %>

location.reload();

app/views/datasets/destroy.js.erb
document.querySelector("[data-dataset-id='<%= @dataset.id %>']").remove();
location.reload();

app/views/datasets/edit.js.erb
function insertForm () {
  let row = document.querySelector("[data-dataset-id='<%= @dataset.id %>']")
  row.outerHTML = "<%= j render 'inline_form', dataset: @dataset, chart: @chart %>"
}

insertForm();

app/views/datasets/update.js.erb
function updateRow() {
  let row = document.querySelector("[data-dataset-id='<%= @dataset.id %>']")
  row.outerHTML = "<%= j render 'show', dataset: @dataset %>"
}

updateRow();
location.reload();