config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

	authenticated do
	  root to: 'charts#index'
	end

	root to: 'pages#home'

  resources :charts, except: [:new, :show] do
    resources :datasets, only: [:create, :update]
  end

  resources :datasets, only: [:edit, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-waterfall">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-waterfall-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-waterfall-right hidden-xs hidden-sm">
    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% if show_export? %>
        <!-- <p><em>Placeholder for save messages</em></p> -->
        <button class="navbar-button-green" id="export_button">EXPORT</button>
      <% end %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-waterfall-item">
        <div class="dropdown">
          <div class="avatar_initials dropdown-toggle", id="navbar-waterfall-menu", data-toggle="dropdown"><h6><%= current_user.user_initials  %></h6></div>
          <!--<= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbar-waterfall-menu", "data-toggle" => "dropdown" %> -->
          <ul class="dropdown-menu dropdown-menu-right navbar-waterfall-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i><%= t(".profile", default: " Profile") %>
              <% end %>
            </li>
            <% if current_user.admin %>
              <li>
                <%= link_to rails_admin_path do %>
                  <i class="fa fa-cog"></i><%= t(".admin", default: " Admin") %>
                <% end  %>
              </li>
            <% end %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-times"></i><%= t(".sign_out", default: " Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>

      <% if show_export? %>
        <!-- <p><em>Placeholder for save messages</em></p> -->
        <%= link_to "EXPORT", new_user_session_path, class: "navbar-button-green" %>
      <% end %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-waterfall-item navbar-waterfall-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-waterfall-item hidden-md hidden-lg">
    <div class="dropdown">
      <!-- <i class="fa fa-arrow-circle-down" aria-hidden="true"></i> -->
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-waterfall-dropdown-menu">
        <% if user_signed_in? %>
          <% if show_export? %>
            <li class="export"><%= link_to "EXPORT", root_path %></li>
          <% end %>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to destroy_user_session_path, method: :delete  do %>
            <%= t(".sign_out", default: "Log out") %>
          <% end %>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>