config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

	authenticated do
	  root to: 'charts#index'
	end

	root to: 'pages#home'

  resources :charts, except: [:new, :show] do
    resources :datasets, only: [:create, :update]
  end

  resources :datasets, only: [:edit, :destroy]
end

app/models/chart.rb
class Chart < ApplicationRecord
  belongs_to :user
  has_many :datasets, dependent: :destroy
  mount_uploader :chart_image, PhotoUploader
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:edit, :edit_wf, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :new, :create, :edit, :edit_wf, :update]
  # helper method to handle guest or logged in users
  helper_method :current_or_guest_user
  helper_method :font_use
  helper_method :colors_selector


  def waterfallplayground
  end

  def index
    @user = current_user
    @charts = Chart.where(user: @user)
  end

  def create
    @chart = Chart.new
    @chart.chart_type = params[:type]
    @chart.user = current_or_guest_user
    @chart.color = "gray" if @chart.chart_type == "waterfall"
    # @chart.save
    if @chart.save
      if @chart.chart_type == "waterfall"
        create_4_default_waterfall_datasets
        respond_to do |format|
          format.html { redirect_to edit_chart_path(@chart)}
          format.js # <-- will render `app/views/charts/create.js.erb`
        end
      else
        create_3_default_datasets
        respond_to do |format|
          format.html { redirect_to edit_chart_path(@chart)}
          format.js # <-- will render `app/views/charts/create.js.erb`
        end
      end
    # else
    #   respond_to do |format|
    #     format.html { render 'charts/show' }
    #     format.js
    #   end
    end
    # redirect_to edit_chart_path(@chart)
  end

  def edit
    @active_tab = params[:active_tab]
    @dataset = Dataset.new
  end

  def update
    # raise
    if @chart.update(chart_params)
      respond_to do |format|
        format.html { redirect_to edit_chart_path(@chart, active_tab: params[:active_tab])}
        format.js # <-- will render `app/views/charts/create.js.erb`
      end
    # else ?
    end
  end

  def destroy
    @chart.destroy
    redirect_to charts_path
  end

  def font_use
    return @chart.font_size if show_export?
    return 8
  end

  def colors_selector
    colors = { yellow: "#FFDB29",
               orange: "#FD7366",
               blue: "#30C2FF",
               purple: "#9E60F8",
               green: "#3EC28F",
               gray: "#141414" }
    return colors
  end

  private

  def create_3_default_datasets
    labels = ["Jan", "Feb", "Mar"]
    values = [3, 1, 5]
    i = 0
    3.times do
      new_dataset = Dataset.new(label: labels[i], value: values[i])
      new_dataset.chart = @chart
      new_dataset.save
      i += 1
    end
  end

  def create_4_default_waterfall_datasets
    labels = ["End of Q1", "Income", "Expenses", "End of Q2"]
    values = [10 , 2 ,  3  , 9 ]
    serietypes = ["baseline", "plus", "less", "baseline"]
    offsets = [ 0 , 10 , 9 , 0 ]
    values_user = [ "10", "2", "-3", "e"]
    i=0
    4.times do
      new_dataset = Dataset.new(label: labels[i], value: values[i], serietype: serietypes[i], offset: offsets[i], value_user: values_user[i])
      new_dataset.chart = @chart
      new_dataset.save
      i += 1
    end
  end

  def set_chart
    @chart = Chart.find(params[:id])
  end

  def chart_params
    params.require(:chart).permit(:title, :subtitle, :notes, :color, :font_size, :chart_type)
  end
end

app/views/charts/_bar.html.erb
<div id="bar-chart">
  <svg width="400" height="400"></svg>
</div>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script>

var data = <%= @chart.datasets.to_json.html_safe %>;

var svg = d3.select("#bar-chart > svg"),
    margin = {top: 20, right: 20, bottom: 30, left: 40},
    width = +svg.attr("width") - margin.left - margin.right,
    height = +svg.attr("height") - margin.top - margin.bottom;

var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
    y = d3.scaleLinear().rangeRound([height, 0]);

var g = svg.append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

x.domain(data.map(function(d) { return d.label; }));
y.domain([0, d3.max(data, function(d) { return d.value; })]);

g.append("g")
    .attr("class", "axis axis--x")
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(x));

g.append("g")
    .attr("class", "axis axis--y")
    .call(d3.axisLeft(y).ticks(10))
  .append("text")
    .attr("transform", "rotate(-90)")
    .attr("y", 6)
    .attr("dy", "0.71em")
    .attr("text-anchor", "end")
    .text("value");

g.selectAll(".bar")
  .data(data)
  .enter().append("rect")
    .attr("class", "bar")
    .attr("x", function(d) { return x(d.label); })
    .attr("y", function(d) { return y(d.value); })
    .attr("width", x.bandwidth())
    .attr("height", function(d) { return height - y(d.value); });

</script>

app/views/charts/_chart_script.html.erb
<script src="https://d3js.org/d3.v4.min.js"></script>

<% colors_hash = {
  "yellow": "#FFDB29",
  "orange": "#FD7366",
  "red": "#F04F2B",
  "blue": "#30C2FF",
  "purple": "#9E60F8",
  "green": "#3EC28F",
  "gray": "#000000",
  "light gray": "#F4F4F4",
  "medium dark gray": "#1A1A1A",
  "dark gray": "#141414"
}
%>

  <!-- This is a custom method to toggle show/hide of export button in navbar -->

<meta charset="utf-8">

<style>

	.axis path,
	.axis line {
	  fill: none;
	  stroke: #000;
	  shape-rendering: crispEdges;
	}

  .axis text {
    font-family: "Arial";
    font-size: <%= font_use - 2 %>px;
    transform: rotate(-45deg);
    text-anchor: end;
  }

	#bar-chart-<%= chart.id %> {
	  fill: <%= colors_hash[chart.color.to_sym] %>;
	}

	.bar {
		opacity: 1;
	}

	.bar:hover {
	  opacity: 0.8;
	}

  .axis--x .tick line{
      visibility:hidden;
    }

	.axis--y {
	  display: none;
	}

  .value {
    fill:white;
    font: <%= chart.font_size %>px;
    font-weight: 400;
    text-anchor: middle;
  }

</style>

<script>

var datasource = <%= chart.datasets.order(:created_at).to_json.html_safe %>;

<% if show_export? %>
  var marginTop = 70;
  var marginBottom = 70;
<% else %>
  var marginTop = 40;
  var marginBottom = 40;
<% end %>

var svg = d3.select("#chart-<%= chart.id %> > svg"),
                    
    margin = {top: marginTop , right: 10, bottom: marginBottom, left: 10},

    width = +svg.attr("width") - margin.left - margin.right,
    height = +svg.attr("height") - margin.top - margin.bottom;

var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
    y = d3.scaleLinear().rangeRound([height, 0]);

var g = svg.append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    x.domain(datasource.map(function(d) { return d.label; }));
    y.domain([0, d3.max(datasource, function(d) { return d.value; })]);

    // add x labels
    g.append("g")
        .attr("class", "axis axis--x")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.axisBottom(x).tickSizeOuter(0))

    // add y labels (vertical axis)
    g.append("g")
        .attr("class", "axis axis--y")
        .call(d3.axisLeft(y).ticks(10))
      .append("text")
        .attr("font-family", "Arial")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("font-size", " <%= font_use %>px")
        .attr("text-anchor", "end")
        .text("value");

    // add title    
    g.append("text")
      .attr("x", (width / 2))
      .attr("y", 0 - (margin.top / 2))
      .attr("text-anchor", "middle")
      .attr("font-family", "Arial")
      .style("font-size", "<%= font_use + 6 %>px")
      .text("<%= chart.title if show_export? %>");

    g.append("text")
      .attr("x", (width / 2))
      .attr("y", 0 - (margin.top / 2) + 25)
      .attr("text-anchor", "middle")
      .attr("font-family", "Arial")
      .style("font-size", "<%= font_use %>px")
      .html("<%= chart.subtitle if show_export? %>");

    // add bars
    g.selectAll(".bar")
      .data(datasource)
      .enter().append("rect")
        .attr("font-family", "Arial")
        .attr("class", "bar")
        .attr("id", "bar-chart-<%= chart.id %>")
        .attr("x", function(d) { return x(d.label); })
        .attr("y", function(d) { return y(d.value); })
        .attr("width", x.bandwidth())
        .attr("height", function(d) { return height - y(d.value); });

    // add labels    
    g.selectAll(".text")
      .data(datasource)
      .enter().append("text")
      .attr("font-family", "Arial")
      .attr("class","value")
      .attr("x", (function(d) { return x(d.label) + x.bandwidth() / 2 ; }))
      .attr("y", function(d) { return y(d.value) + 1; })
      .attr("dy", "<%= font_use %>px")
      .style("font-size", "<%= font_use %>px")
      .text(function(d) { return d.value; });

</script>

app/views/charts/_chart_script_bar.html.erb
<script src="https://d3js.org/d3.v4.min.js"></script>

<% colors_hash = colors_selector %>

<meta charset="utf-8">

<style>

	.axis path,
	.axis line {
	  fill: none;
	  stroke: #000;
	  shape-rendering: crispEdges;
	}

  .axis text {
    font-family: "Arial";
    font-size: <%= font_use - 2 %>px;
    transform: rotate(-45deg);
    text-anchor: end;
  }

	#bar-chart-<%= chart.id %> {
	  fill: <%= colors_hash[chart.color.to_sym] %>;
	}

	.bar {
		opacity: 1;
	}

	.bar:hover {
	  opacity: 0.8;
	}

  .axis--x .tick line{
      visibility:hidden;
    }

	.axis--y {
	  display: none;
	}

  .value {
    fill: white;
    font: <%= chart.font_size %>px;
    font-weight: 400;
    text-anchor: middle;
  }

</style>

<script>

var datasource = <%= chart.datasets.order(:created_at).to_json.html_safe %>;

<% if show_export? %>
  var marginTop = 70;
  var marginBottom = 100;
  var marginSide = 50;
  var positionHeight = 4;
<% else %>
  var marginTop = 30;
  var marginBottom = 55;
  var marginSide = 10;
  var positionHeight = 2.5;
<% end %>

var svg = d3.select("#chart-<%= chart.id %> > svg");

svg.call(responsivefy);

svg = svg,
    margin = {top: marginTop , right: marginSide, bottom: marginBottom, left: marginSide},
    width = +svg.attr("width") - margin.left - margin.right,
    height = +svg.attr("height") - margin.top - margin.bottom;

var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
    y = d3.scaleLinear().rangeRound([height, 0]);

var g = svg.append("g").attr("transform", "translate(" + margin.left + "," + height / positionHeight + ")");

    x.domain(datasource.map(function(d) { return d.label; }));
    y.domain([0, d3.max(datasource, function(d) { return d.value; })]);

    // add x labels
    g.append("g")
        .attr("class", "axis axis--x")
        .attr("transform", "translate(0," + height + ")")
        .call(d3.axisBottom(x).tickSizeOuter(0))

    // add y labels (vertical axis)
    g.append("g")
        .attr("class", "axis axis--y")
        .call(d3.axisLeft(y).ticks(10))
      .append("text")
        .attr("font-family", "Arial")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("font-size", " <%= font_use %>px")
        .attr("text-anchor", "end")
        .text("value");

    // add title
    g.append("text")
      .attr("x", (width / 2))
      .attr("y", 0 - (margin.top / 2) - 20)
      .attr("text-anchor", "middle")
      .attr("font-family", "Arial")
      .style("font-size", "<%= font_use + 6 %>px")
      .text("<%= chart.title.html_safe if show_export? %>");

    // add subtitle
    g.append("text")
      .attr("x", (width / 2))
      .attr("y", 0 - (margin.top / 2))
      .attr("text-anchor", "middle")
      .attr("font-family", "Arial")
      .style("font-size", "<%= font_use %>px")
      .html("<%= chart.subtitle.html_safe if show_export? %>");

    // add bars
    g.selectAll(".bar")
      .data(datasource)
      .enter().append("rect")
      .attr("font-family", "Arial")
      .attr("class", "bar")
      .attr("id", "bar-chart-<%= chart.id %>")
      .attr("y", height) // starting point of transition
      .attr("height", 0) // starting point of transition
      .attr("x", function(d) { return x(d.label); })
      .attr("width", x.bandwidth())
      .transition()
        .delay(300)
        .duration(600)
        .ease(d3.easeQuad)
        .attr("y", function(d) { return y(d.value); })
        .attr("height", function(d) { return height - y(d.value); });

    // add labels
    g.selectAll(".text")
      .data(datasource)
      .enter().append("text")
      .attr("font-family", "Arial")
      .attr("class","value")
      .attr("x", (function(d) { return x(d.label) + x.bandwidth() / 2 ; }))
      .attr("y", function(d) { return y(d.value) + 1; })
      .attr("dy", "<%= font_use %>px")
      .style("font-size", "<%= font_use %>px")
      .text(function(d) { return d.value; });

    // make chart responsive
    function responsivefy(svg) {

      // get container and svg aspect ratio
      var container = d3.select(svg.node().parentNode),
        widthSvg = parseInt(svg.style("width")),
        heightSvg = parseInt(svg.style("height")),
        aspect = widthSvg / heightSvg;

      // add viewBox and preserveAspectRatio properties
      svg.attr("viewBox", "0 0 " + widthSvg + " " + heightSvg)
        .attr("preserveAspectRatio", "xMinYMid")
        .attr("width", widthSvg)
        .attr("height", heightSvg)
    }

</script>

app/views/charts/_chart_script_line.html.erb
<script src="https://d3js.org/d3.v4.min.js"></script>

<% colors_hash = colors_selector %>

<!-- This is a custom method to toggle show/hide of export button in navbar -->

<meta charset="utf-8">

<style>

  .axis path,
  .axis line {
    fill: none;
    stroke: #000;
    shape-rendering: crispEdges;
  }

  #path-chart-<%= chart.id %> {
    stroke: <%= colors_hash[chart.color.to_sym] %>;
  }

  .path {
    opacity: 1;
  }

  .path:hover {
    opacity: 0.8;
  }

  .axis text {
    font-family: "Arial";
    font-size: <%= font_use - 2 %>px;
    transform: rotate(-45deg);
    text-anchor: end;
  }

  .axis--x .tick line{
      visibility:hidden;
    }

  .axis--y {
    display: none;
  }

  .value {
    fill:black;
    font: <%= chart.font_size %>px;
    font-weight: 400;
    text-anchor: middle;
  }

</style>

<script>
// set margins
<% if show_export? %>
  var marginTop = 70;
  var marginBottom = 100;
  var marginSide = 50;
  var positionHeight = 4;
<% else %>
  var marginTop = 30;
  var marginBottom = 55;
  var marginSide = 10;
  var positionHeight = 2.5;
<% end %>

var datasource = <%= chart.datasets.order(:created_at).to_json.html_safe %>;


var svg = d3.select("#chart-<%= chart.id %> > svg");

svg.call(responsivefy);

svg = svg,
    margin = {top: marginTop , right: marginSide, bottom: marginBottom, left: marginSide},
    width = +svg.attr("width") - margin.left - margin.right,
    height = +svg.attr("height") - margin.top - margin.bottom;

var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
    y = d3.scaleLinear().rangeRound([height, 0]);

var g = svg.append("g").attr("transform", "translate(" + margin.left + "," + height / positionHeight + ")");

var line = d3.line()
    .x(function(d) { return x(d.label) + x.bandwidth()/2 ; })
    .y(function(d) { return y(d.value); });

// var lineFin = d3.line()
//     .x(function(d) { return x(d.label) + x.bandwidth()/2 ; })
//     .y(function(d) { return y(d.value); });

    x.domain(datasource.map(function(d) { return d.label; }));
    y.domain([0, d3.max(datasource, function(d) { return d.value; })]);

    // add x labels
      g.append("g")
          .attr("class", "axis axis--x")
          .attr("transform", "translate(0," + height + ")")
          .call(d3.axisBottom(x).tickSizeOuter(0))

    // add y labels (vertical axis)
      g.append("g")
          .attr("class", "axis axis--y")
          .call(d3.axisLeft(y).ticks(10))
        .append("text")
          .attr("font-family", "Arial")
          .attr("transform", "rotate(-90)")
          .attr("y", 6)
          .attr("font-size", " <%= font_use %>px")
          .attr("text-anchor", "end")
          .text("value");

    // add title
    g.append("text")
      .attr("x", (width / 2))
      .attr("y", 0 - (margin.top / 2) - 20)
      .attr("text-anchor", "middle")
      .attr("font-family", "Arial")
      .style("font-size", "<%= font_use + 6 %>px")
      .text("<%= chart.title.html_safe if show_export? %>");

    // add subtitle
    g.append("text")
      .attr("x", (width / 2))
      .attr("y", 0 - (margin.top / 2))
      .attr("text-anchor", "middle")
      .attr("font-family", "Arial")
      .style("font-size", "<%= font_use %>px")
      .html("<%= chart.subtitle.html_safe if show_export? %>");

    // add line
    g.append("path")
      .datum(datasource)
      .attr("class", "path")
      .attr("id", "path-chart-<%= chart.id %>")
      .attr("fill", "none")
      .attr("stroke-linejoin", "round")
      .attr("stroke-linecap", "round")
      .attr("stroke-width", 1.5)
      .attr("d", line)
      .transition()
        .delay(300)
        .duration(600)
        .ease(d3.easeQuad)
        .attr("d", line)
        .attrTween("stroke-dasharray", tweenDash);

    // add labels
    g.selectAll(".text")
      .data(datasource)
      .enter().append("text")
      .attr("font-family", "Arial")
      .attr("class","value")
      .attr("x", (function(d) { return x(d.label) + x.bandwidth() / 2 ; }))
      .attr("y", function(d) { return y(d.value) - 20; })
      .attr("dy", "<%= font_use %>px")
      .style("font-size", "<%= font_use %>px")
      .style("opacity", 0)
      .text(function(d) { return d.value; })
      .transition()
      .ease(d3.easeQuad)
      .delay(700)
      .on("start", function repeat() {
        var t = d3.active(this)
          .duration(600)
          .style("opacity", 1)
      });

    // function for transition
    function tweenDash() {
        var l = this.getTotalLength(),
            i = d3.interpolateString("0," + l, l + "," + l);
        return function (t) { return i(t); };
    }

    // make chart responsive
    function responsivefy(svg) {

      // get container and svg aspect ratio
      var container = d3.select(svg.node().parentNode),
        widthSvg = parseInt(svg.style("width")),
        heightSvg = parseInt(svg.style("height")),
        aspect = widthSvg / heightSvg;

      // add viewBox and preserveAspectRatio properties
      svg.attr("viewBox", "0 0 " + widthSvg + " " + heightSvg)
        .attr("preserveAspectRatio", "xMinYMid")
        .attr("width", widthSvg)
        .attr("height", heightSvg);
    }

</script>

app/views/charts/_design_section.html.erb
<%= simple_form_for(@chart) do |f| %>
  <h5 class="margin-top">FONT-SIZE</h5>
  <div class="font-size-entry">
    <div class="font-size-picker">
      <%= f.input :font_size, label: false, collection: [ 8, 12, 16, 24, 32 ] %>
    </div>
    <div class="font-size-btn">
      <%= f.button :button, name: "active_tab", value: "design" do %>
        <i class="fa fa-check-square-o" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>
<% end %>

<% colors = colors_selector %>

<div class="color-selection">
  <h5>COLOR</h5>
  <% colors.each do |color, value| %>
    <%= link_to chart_path(chart: {color: color}, active_tab: "design"), method: :patch do %>
      <div class="color-box" style="background-color:<%= value %>"></div>
    <% end %>
  <% end %>
</div>

<% unless @chart.chart_type == "waterfall" %>

  <div class="type-selection">
    <h5>TYPE</h5>
    <% types = ["bar", "line", "pie"] %>
    <% types.each do |type| %>
      <%= link_to chart_path(chart: {chart_type: type}, active_tab: "design"), method: :patch do %>
        <div class="type-button">
          <i class="fa fa-<%= type %>-chart" aria-hidden="true"></i>
        </div>
      <% end %>
    <% end %>
  </div>

<% end %>

app/views/charts/_form.html.erb
<!-- This is the form used to add a chart title and chart subtitle -->
<%= simple_form_for(@chart) do |f| %>
  <%= f.input :title, placeholder: "Title", label: false %>
  <%= f.input :subtitle, placeholder: "Subtitle", label: false %>
  <%= f.button :button do %>
    <i class="fa fa-check-square-o" aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/charts/_memo.erb
<div class="memo">
  <h1 class="memo-text text-center">
    <i class="fa fa-bar-chart" aria-hidden="true"></i>
  </h1>
  <h3 class="memo-text text-center">
    Your first chart is going to be amazing!
  </h3>
  <p class="memo-text text-center">
    Everything you design will appear here.
  </p>
</div>

app/views/charts/_notes_section.html.erb
<div class="notes">
  <p id="notes-content">
    <%= @chart.notes %>
  </p>
  <i class="fa fa-pencil" aria-hidden="true" id="pencil-notes-edit"></i>
</div>

<%= content_for(:after_js) do %>
  <script>
    const formNotes = document.getElementById('notes-form');
    const notes = document.getElementById('chart-notes');
      const pencilNotes = document.getElementById("pencil-notes-edit");
      pencilNotes.addEventListener("click", (event) => {
        event.preventDefault;
        toggleNotes(formNotes, notes)
      });

        function toggleNotes(formNotes, notes){
          formNotes.classList.toggle("hidden");
          notes.classList.toggle("hidden")
        }
  </script>
<% end %>

app/views/charts/_past_projects.html.erb
<div class="row">
  <% @charts.order(updated_at: :desc).each do |chart| %>

    <div class="col-xs-12 col-sm-4 col-md-3">
      <div class="card">
        <%= link_to edit_chart_path(chart) do %>
           <div class="card-image" id="chart-<%= chart.id %>">
              <div class="info-tag"><i class="fa fa-info-circle">
              </i>
                <span class="tooltiptext">
                  <p><strong><%= chart.title %></strong></p>
                  <p><%= chart.subtitle %></p>
                  <p><em>Last update: <%= chart.updated_at %></em></p>
                </span>
              </div>
             <svg></svg>
               <%= render "chart_script_#{chart.chart_type}", chart: chart %>
            <!-- <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<= image_path chart.chart_image %>')">
            </div> -->
           </div>
        <% end %>

        <div class="body">
          <div class="card-title">
            <%= link_to chart.title, edit_chart_path(chart), class:"chart-title" %>
          </div>
          <div class="card-delete">
            <i class="fa fa-trash-o" data-toggle="modal" data-target="#myModal-<%= chart.id %>" data-id-chart="<%= chart.id %>"></i>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal-<%= chart.id %>" tabindex="0" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">WARNING</h5>
          </div>
          <div class="modal-body">
            <h5>Your chart will be permanently removed.</h5>
            <h5>Are you sure you want to delete it?</h5>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= link_to chart_path(chart), method: :delete do  %>
              <button type="button" class="btn btn-primary">Confirm</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

<!-- Button trigger modal -->

app/views/charts/_title_section.html.erb
<div class="all-titles">
  <div id="chart-title">
    <h4><%= @chart.title %></h4>
  </div>
  <div id="chart-subtitle">
    <h5><%= @chart.subtitle %>
      <i class="fa fa-pencil" aria-hidden="true" id="pencil-edit"></i>
  </h5>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    const form = document.getElementById('titles-form');
    const titles = document.getElementById('chart-titles');
      const pencil = document.getElementById("pencil-edit");
      pencil.addEventListener("click", (event) => {
        event.preventDefault;
        form.classList.toggle("hidden");
        titles.classList.toggle("hidden")
      });
  </script>
<% end %>

app/views/charts/edit.html.erb
<div class="container-fluid half-half">
  <div class="row main-container">
    <div class="col-xs-12 col-sm-6">
      <ul class="nav nav-tabs ">


        <li class="<%= 'active' unless @active_tab == "design" %>"><a data-toggle="tab" href="#data">DATA</a></li>
        <li class="<%= 'active' if @active_tab == "design" %>"><a data-toggle="tab" href="#design">DESIGN</a></li>
        <li><a data-toggle="tab" href="#notes">NOTES</a></li>
      </ul>
      <div class="tab-content">
        <div id="data" class="tab-pane fade <%= 'in active' unless @active_tab == "design" %>">
          <div id="chart-titles">
            <%= render 'charts/title_section' %>
          </div>
          <div id="titles-form" class="hidden">
            <%= render 'charts/form' %>
          </div>
            <div id="data-sets-table">
              <div class="table-heading">
                <div class="table-cell">
                  <p>LABEL</p>
                </div>
                <div class="table-cell">
                  <p>VALUE</p>
                </div>
              </div>
              <% @chart.datasets.order(:created_at).each do |dataset| %>
                <%= render 'datasets/show', dataset: dataset %>
              <% end %>
            </div>
            <%= render 'datasets/form', chart: @chart, dataset: @dataset %>
        </div>
        <div id="design" class="tab-pane fade <%= 'in active' if @active_tab == "design" %>">
          <%= render 'charts/design_section' %>
        </div>
        <div id="notes" class="tab-pane fade <%= 'in active' if @active_tab == "notes" %>" >
          <div id="chart-notes">
            <%= render 'charts/notes_section' %>
          </div>
          <div id="notes-form" class="hidden">
            <%= render 'charts/form_notes' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="chart-area" id="chart-<%= @chart.id %>">
        <svg width="600" height="500" id="chart-d3" data-title="<%= @chart.title %>"></svg>
      </div>
    </div>
  </div>
</div>

<%= render "chart_script_#{@chart.chart_type}", chart: @chart%>